on: [push]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    name: A lighthouse test job
    steps:
      - name: Generate lighthouse data
        id: lighthouse-check
        uses: chris-ivan/test-lighthouse-action@0.2
        with:
          who-to-greet: "Mona the Octocat"
